version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/cloudfunctions"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 5
    ignore:
      - dependency-type: "dev"
